server:
    port: 9001

spring:
    application:
        name: api-new
    main:
        allow-bean-definition-overriding: true

management:
    endpoints:
        web:
            exposure:
                include: ["health","info","hystrix.stream"]
            cors:
                allowed-origins: "*"
                allowed-methods: "*"
feign:
    hystrix:
        enabled: true
hystrix:
    command:
        default:
            execution:
                timeout:
                    enabled: true
                isolation:
                    thread:
                        timeoutInMilliseconds: 1000
    threadpool:
        default:
            coreSize:
                20
