server:
    port: 9000

spring:
    application:
        name: api-community

management:
    endpoints:
        web:
            exposure:
                include: ["health","info","hystrix.stream"]
            cors:
                allowed-origins: "*"
                allowed-methods: "*"
