server:
    port: 9000

spring:
    application:
        name: api-community

#feign:
#    hystrix:
#        enabled: true
#turbine:
#    app-config: soa-content,soa-group
#    aggregator:
#        cluster-config: default
#    cluster-name-expression: new String("default")
#    instanceUrlSuffix: /hystrix.stream

management:
    endpoints:
        web:
            exposure:
                include: ["health","info","hystrix.stream"]
            cors:
                allowed-origins: "*"
                allowed-methods: "*"


hystrix:
    command:
        default:
            execution:
                timeout:
                    enabled: true
                isolation:
                    thread:
                        timeoutInMilliseconds: 1000
    threadpool:
        default:
            coreSize: 20
