server:
    port: 9001

spring:
    application:
        name: api-new

feign:
    hystrix:
        enabled: true
turbine:
    app-config: soa-content,soa-group
    aggregator:
        cluster-config: default
    cluster-name-expression: new String("default")
    instanceUrlSuffix: /hystrix.stream

management:
    endpoints:
        web:
            exposure:
                include: ["health","info","hystrix.stream"]
            cors:
                allowed-origins: "*"
                allowed-methods: "*"
