server:
    port: 8763

spring:
    application:
        name: hystrix-turbine


turbine:
    app-config: api-new,api-community
    cluster-name-expression: new String("default")
    combine-host-port: true